/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package militery.base.management.system;

import com.mongodb.MongoClient;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;
import com.mongodb.client.model.Filters;
import org.bson.Document;
import org.bson.conversions.Bson;

/**
 *
 * @author M S I
 */
public class viewsoldire extends javax.swing.JFrame {
     MongoClient mongo;
     MongoDatabase db;
     MongoCollection<org.bson.Document> collection;
    /**
     * Creates new form viewsoldire
     */
    public viewsoldire() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        nametext = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        agetext = new javax.swing.JTextField();
        religiontext = new javax.swing.JTextField();
        nictext = new javax.swing.JTextField();
        clear = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nametext1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(java.awt.Color.lightGray);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jLabel1.setText("View Soldire Details");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 29, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel2.setText("Soldier ID");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 119, -1, -1));

        id.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jPanel2.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 115, 313, 37));

        search.setBackground(new java.awt.Color(0, 204, 0));
        search.setFont(new java.awt.Font("Serif", 1, 20)); // NOI18N
        search.setForeground(new java.awt.Color(255, 255, 255));
        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jPanel2.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(677, 114, -1, -1));

        nametext.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jPanel2.add(nametext, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 248, 310, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 1, 22)); // NOI18N
        jLabel4.setText("Address");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 465, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 1, 22)); // NOI18N
        jLabel5.setText("Age");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 398, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 1, 22)); // NOI18N
        jLabel6.setText("Religion");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 556, -1, -1));

        agetext.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jPanel2.add(agetext, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 402, 310, -1));

        religiontext.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jPanel2.add(religiontext, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 558, 310, -1));

        nictext.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jPanel2.add(nictext, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 467, 310, -1));

        clear.setBackground(new java.awt.Color(0, 102, 255));
        clear.setFont(new java.awt.Font("Serif", 1, 20)); // NOI18N
        clear.setForeground(new java.awt.Color(255, 255, 255));
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel2.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(719, 658, -1, -1));

        jButton3.setBackground(new java.awt.Color(255, 0, 0));
        jButton3.setFont(new java.awt.Font("Serif", 1, 20)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 658, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 1, 22)); // NOI18N
        jLabel7.setText("Last Name");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 317, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 1, 22)); // NOI18N
        jLabel8.setText("First Name");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 244, -1, -1));

        nametext1.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jPanel2.add(nametext1, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 321, 310, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 26, 840, 730));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 800));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
      /*  int number = Integer.parseInt(id.getText());
        try {
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/main_base","root","root");

            // Prepare a SQL query to retrieve data by ID
            String sql = "SELECT first_name,age,NIC,religion FROM soldiers_data WHERE soldier_id = ?";
            PreparedStatement preparedStatement = connection.prepareStatement(sql);
            preparedStatement.setInt(1, number);

            // Execute the query
            ResultSet resultSet = preparedStatement.executeQuery();

            if (resultSet.next()) {
                // Display the results in the text fields
                nametext.setText(resultSet.getString("first_name"));
                agetext.setText(String.valueOf(resultSet.getInt("age")));
                nictext.setText(resultSet.getString("NIC"));
                religiontext.setText(resultSet.getString("religion"));
            } else {
                // No data found for the given ID
                //JOptionPane.showMessageDialog(this, "Data not found for ID " + id, "Not Found", JOptionPane.INFORMATION_MESSAGE);
                JOptionPane.showMessageDialog(this, "Data not found ! ");
            }

            // Close resources
            resultSet.close();
            preparedStatement.close();
            connection.close();
        } catch (SQLException ex) {

            Logger.getLogger(Transer.class.getName()).log(Level.SEVERE, null, ex);
        }*/
                    mongo=new MongoClient("localhost",27017);
         db=mongo.getDatabase("SoldireManagement");
         collection=db.getCollection("SoldiresData");
         System.out.println("Collection created");
          String idToSearch = id.getText();
Bson filter = Filters.eq("NIC", idToSearch); // Assuming _id is the field in MongoDB
Document result = collection.find(filter).first();

if (result != null) {
    // Data found, display or process the result
String fieldValue1 = result.getString("FirstName"); // Replace "field1" with the actual field name in your document
    String fieldValue2 = result.getString("LastName"); // Replace "field2" with the actual field name in your document
    String fieldValue3 = result.getString("Age");
    String fieldValue4 = result.getString("Address");
    String fieldValue5 = result.getString("Religion");

    nametext.setText(fieldValue1);
    nametext1.setText(fieldValue2);
     agetext.setText(fieldValue3);
     nictext.setText(fieldValue4);
    religiontext.setText(fieldValue5);

    
} else {
    // Data not found
    System.out.println("Not found");
}
         
    }//GEN-LAST:event_searchActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        nametext.setText("");
                nametext1.setText("");

        agetext.setText("");
        nictext.setText("");
        religiontext.setText("");
        id.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        home menu=new home();
        menu.show();
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewsoldire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewsoldire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewsoldire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewsoldire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewsoldire().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField agetext;
    private javax.swing.JButton clear;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField nametext;
    private javax.swing.JTextField nametext1;
    private javax.swing.JTextField nictext;
    private javax.swing.JTextField religiontext;
    private javax.swing.JButton search;
    // End of variables declaration//GEN-END:variables
}
